ao-org/argentum-online-client

CODIGO/General.bas
some resources try to load before the compression password is generated and fail
=> fix resource load order

CODIGO/Declares.bas, CODIGO/ModLogin.bas, CODIGO/ModSettings.bas, CODIGO/Protocol.bas, CODIGO/ao20audio.bas, CODIGO/clsAudioEngine.cls
We can now associate a label to each sound which gives better control to manage playback. We can now set a sound to loop and give it a label which can then used to stop it.
To demostrate this patch adds a sound effect when characters meditate: during meditation a small effect could be heard and this is using either channel left/right depending on the character position.
=> Support for audio labels in tracks

CODIGO/clsAudioEngine.cls
1) Midis were not playing properly because a type error when comparing the song number
2) Added a call to DirectMusicPerformance8::CloseDown to properly shutdown the sound
=> Audios fixes

CODIGO/Application.bas, CODIGO/General.bas, CODIGO/ao20config.bas
This file creeps up to many GB in size. We simply delete it when the game is launched and keep the errors of the current session.
=> Delete Errores.log when game starts

CODIGO/TileEngine.bas, CODIGO/clsAudioEngine.cls
Fixes ao-org/argentum-online-server#456
Agrego un label a los pasos para poder detener el sonido de los pasos anteriores (por personaje).
También arreglo el sonido del caballo cuando está sobre piso.
=> Fix sonido al navegar y cabalgar

CODIGO/frmGuildAdm.frm
Solo cambio en la UI vieja. Si bien se mostraban todos los clanes, en el select se leía "Legión Oscura" por defecto
=> La lista de clanes debe mostrar alineación Todos por defecto

CODIGO/Protocol.bas, CODIGO/TileEngine.bas, CODIGO/TileEngine_Chars.bas, CODIGO/ao20audio.bas, CODIGO/engine.bas
Ahora ningún sonido de usuario debería escucharse por fuera de la pantalla.
Vuelvo la atenuación de volúmen al cálculo que tenía antes.
=> Chequeos de sonido en PC area + revierto la atenuación de volúmen

CODIGO/Protocol.bas
Se eliminaba el char del cliente sin tener en cuenta el clan
=> Fix invi en clanes nivel 6

CODIGO/General.bas, CODIGO/Protocol.bas, CODIGO/TileEngine.bas, CODIGO/TileEngine_Chars.bas
- Agrego flag para saber si un char está meditando, en base a si tiene un FX al crear o cambiar el char
- Usando el flag evito borrar el char hasta que deje de meditar (para ver la meditación aunque esté invisible)
- El checkeo de rango de visión de la meditación lo dejo sólo para reproducir el sonido y no para detenerlo. Y tampoco afecta la animación. Así no queda el sonido loopeando ni la meditación bugueada.
=> Fix meditar invi

git_ignore_case.sh
This script aims to automate the tedious task of filtering out case-only changes made by the VB6 IDE, allowing you to focus on the meaningful changes in your git diff output.
Key Enhancements:
- Function Usage: Encapsulated the processing logic into a process_file function to avoid code duplication and improve readability.
- Case Normalization: Used awk to convert both the original and the modified file contents to lowercase before diffing. This approach helps to ignore case-only differences.
- Conditional Patch Application: The script now checks if the patch file ($PATCHFILE) is non-empty before applying it. This ensures that changes are only made if there are actual differences beyond case changes.
- File Handling: Improved the handling of file paths in the script to ensure it works …
=> Applied improvements for unwanted diff from VB6 IDE

CODIGO/ModUtils.bas, CODIGO/Recursos.bas
Reverts ao-org/argentum-online-client#354
Revierto PR por que no compila.
```
Compile Error in File 'C:\re20-cliente-master\CODIGO\Recursos.bas', Line 1758 : Next without For
Build of 'Argentum.exe' failed.
```
@Centorios
=> Revert "NoMapInfo prop for npcs"

CODIGO/ModTutorial.bas, CODIGO/Protocol.bas, CODIGO/TileEngine_Map.bas
Recent changes broke the skills button and it throw this error:
```
Error: 9
Descripcion: El subíndice está fuera del intervalo
Componente: frmMain.EstadisticasBoton_MouseUp
Linea: 0
Fecha y Hora: 05-27-2024-02:11:41
```
Now it works fine and the NPCs are rendered fine in the tutorial
=> Fixed mostrarCartel function for tutorial and skills button error

CODIGO/ModMetereologia.bas
Problema: Los dungeon oscuros tienen muy poca iluminación por defecto, y los jugadores clickean en el mapa por necesidad de ver mejor, ya que hacer esto cambia la ilumiación del mapa. La única excepción son los polos, en donde si cambias la iluminación te quedas ciego de lo blanco que es.
Solución: Más allá de que clickear el mapa no debería cambiar la iluminación, subí la ilumnación de los dungeon para que la gente no tenga la necesidad de clickear el mapa:
- Se ve más iluminado dentro de los dungeon que son oscuros, como DV, permitiendo conservar el efecto de las antorchas pero logrando mejor visibilidad
- No hace falta clickear fuera para dungeon como polo ya que por defecto se ve bien.
=> Iluminación de los dungeons

CODIGO/ModUtils.bas, CODIGO/TileEngine.bas, CODIGO/frmConnect.frm
Aceptar primero el PR del server así se actualiza el mapa de Forgat a su nueva ubicación!
Con este PR hago lo siguiente:
1) Dejo como opción de hogar de nacimiento a Ulla, Nix, Arghal y Forgat en la creación de personaje
2) Arreglo los botones para cambiar de ciudad de nacimiento en la creación de personaje
3) Evito que una variable utilizada para graficar grh sea 0, ya que solo aparece solo denominadores y hay casos en los que el cliente intenta dividir por 0
=> Corrijo el hogar en la creación de personaje

CODIGO/ModUtils.bas, CODIGO/frmConnect.frm
Creo funciones nuevas para la selección de clase al crear personaje que logran lo siguiente:
- Eliminar la selección del Ladrón y el Pirata, ya que se encuentran "deshabilitados" en el juego
- Ordenar las clases de más mágicas a menos mágicas, arrancando en Mago/Druida y terminando en Guerrero/Trabajador
- Que la primer clase por defecto sea Mago
=> Clases en creación de personaje

CODIGO/BabelUI.bas, CODIGO/frmOpciones.frm
Desactivo la ui experimental: pongo en 0 el valor de UseExperimentalUI al momento de chequear  la configuración, y agrego un mensaje  al querer activarla/desactivarla desde opciones
=> Desactivo ui experimental

Argentum20.vbp, CODIGO/VBJson/cStringBuilder.cls
This pull request includes a small change to the `Argentum20.vbp` file. The change adds a new class module `cStringBuilder` to the project.
* [`Argentum20.vbp`](diffhunk://#diff-0c41d85c39ae27fb07f7bb4db00669068354bbdfaa87f58ba1097f97381b1db5R153): Added `Class=cStringBuilder; CODIGO\VBJson\cStringBuilder.cls` to include the `cStringBuilder` class module in the project.
=> Added missing module to build the project

CODIGO/frmMain.frm
Oculto el lbl de oxígeno en frmMain (ya estaba oculto pero faltaba poner en false un valor para que no aparezca luego de ser golpeado o de cambiar al menú y volver a los stats)
=> Oculto lbl de oxígeno

CODIGO/frmMapaGrande.frm
Este cambio hace que tanto la información como la vista previa de los npcs se muestre mejor en la ventana del mapa (frmMapaGrande).
=> Optimización de la información y vista previa de npcs en mapa

CODIGO/Graficos_Particulas.bas
This pull request focuses on enhancing error handling and improving code readability in the `General_Particle_Create` function within the `CODIGO/Graficos_Particulas.bas` file. The most important changes include adding checks for array initialization, ensuring bounds of indices, and refactoring the code for better clarity.
Improvements to error handling:
* Added a check to ensure the `StreamData` array is initialized before proceeding with particle creation.
* Included a validation to ensure `ParticulaInd` is within valid bounds, and logged errors if it is not.
* Added a check to ensure the `colortint` array within `StreamData` has enough elements before accessing it.
Code readability improvements:
* Declared the `rgb_list` array in a safer manner and refactored the `SetRGBA` calls for …
=> Added null pointer checks and logs in General_Partcile_Create

CODIGO/clsCursor.cls
This pull request includes several changes to the `Parse_Form` method in the `CODIGO/clsCursor.cls` file. The changes focus on improving code clarity and ensuring proper initialization of variables.
Improvements to code clarity and variable initialization:
* Added a default value for `lngHandle` to prevent uninitialized variable issues.
* Reformatted the `Select Case` block for better readability and maintainability.
* Maintained minimal error handling inside the loop and ensured consistent formatting.
* Ensured consistent formatting when setting the form's mouse properties.
* Retained error logging with the exact line number where the error occurred for better debugging.
=> Fixed Statements and labels invalid between Select Case and first Case

CODIGO/Graficos_Particulas.bas
Reverts ao-org/argentum-online-client#425
Compile Error in File 'C:\Program Files (x86)\Jenkins\workspace\re20-cliente-pull-requests\CODIGO\Graficos_Particulas.bas', Line 1251 : Only user-defined types defined in public object modules can be coerced to or from a variant or passed to late-bound functions
Needs to be fixed later.
=> Revert "Added null pointer checks and logs in General_Partcile_Create"

CODIGO/Protocol.bas
Cuando te conectas con un personaje en la cuenta por primera vez, el label que indica en que mapa estas aparece como "Mapa desconocido", o al cambiar el personaje, el label aparece con el nombre del mapa del anterior usuario que estaba conectado en esa cuenta. Este no se actualiza hasta cambiar de mapa. Esta linea lo que hace es actualizar ese label para que al entrar se muestre correctamente.
=> Actualizar nombre del mapa al conectarse

CODIGO/Graficos_Particulas.bas
This pull request includes significant changes to the `General_Particle_Create` function in the `CODIGO/Graficos_Particulas.bas` file to improve error handling and code clarity. The changes ensure that array bounds are checked before accessing elements and that key properties are extracted and assigned more safely.
Improvements to error handling and code clarity:
* [`CODIGO/Graficos_Particulas.bas`](diffhunk://#diff-2c6c384e5848a397cf61df2a088e736ee56dac4bd4dca8a7bc1742738eafe393L1249-R1326): Added checks to ensure the `StreamData` array is initialized and non-empty before proceeding with operations.
* [`CODIGO/Graficos_Particulas.bas`](diffhunk://#diff-2c6c384e5848a397cf61df2a088e736ee56dac4bd4dca8a7bc1742738eafe393L1249-R1326): Added bounds checking for `ParticulaInd` to ensure it is …
=> Sanity check in General_Particle_Create and improved readability

CODIGO/clsNetWriter.cls, CODIGO/modNetwork.bas
When using DPLAY, the client was sending two commands with eLoginExistingChar.
Solved by removing the call to Login when we get the event ConnectionComplete
=> DPLAY fixed duplicated Login messages

CODIGO/frmMain.frm
Si el usuario está muerto se desactivan los contadores, de esta forma luego de revivir no vuelven a aparecer hasta que se dope nuevamente.
=> Desactivo contadores si el usuario está muerto

CODIGO/Protocol.bas
Actualmente cuando se quiere ver cuántos npcs llevas matado en la quest, si mataste más de los requeridos, se muestra 11/10 por ejemplo. Esto sucede porque el condicional es si la cantidad es = a 0. Como el cálculo que se hace es cantidadnpc - matados = cantidad, si mataste más npcs de los requeridos, el valor de cantidad da -1 y de esa forma entra directamente en el Else, mostrando como resultado un número mayor de npcs matados que los requeridos (11/10 por ejemplo). Con este cambio al matar los npcs requeridos o más, entra correctamente en el Else y se muestra el OK correspondiente.
=> Arreglo de conteo en quest: muestra "OK" al alcanzar o superar la cantidad de npcs requeridos

CODIGO/ModUtils.bas, CODIGO/Protocol.bas, CODIGO/frmQuestInfo.frm
Este cambio muestra la clase requerida para iniciar una quest a través de RequiredClass en quest.dat
Necesario para que funcione: https://github.com/ao-org/argentum-online-server/pull/721
=> Mostrar clase requerida para iniciar quest

CODIGO/frmMain.frm
This pull request includes changes to the `CODIGO/frmMain.frm` file, specifically commenting out the calls to the `handleGoldNExpTrackerPictureLogic` method in two places. This change appears to be aimed at temporarily disabling the logic related to updating the gold and experience tracker images.
The most important changes include:
* [`Private Sub loadButtons()`](diffhunk://#diff-26b9550687feec6c69ceaf6dbfb8b53e1ff77dda0c272381c8a5823e870d8b0fL1719-R1719): Commented out the call to `handleGoldNExpTrackerPictureLogic` to disable the gold and experience tracker picture logic.
* `Private Sub Form_MouseMove(Button As Integer, Shift As Integer, x As Single, y A)`: Commented out the call to `handleGoldNExpTrackerPictureLogic` to prevent the tracker picture logic from being executed on mouse …
=> Commented out exp/gold tracker until is fixed

CODIGO/frmMapaGrande.frm
Este cambio soluciona un bug en el que el PlayerView que muestra los npcs en el mapa no se limpiaba correctamente al clickear un mapa sin NPCs. La función picMap_MouseDown ahora se encarga de limpiar el contenido de PlayerView utilizando Me.PlayerView.Cls cuando el nuevo mapa seleccionado no tiene NPCs. Esto asegura que el PictureBox no quede con el dibujo del NPC anterior.
=> Fix: Limpieza del PlayerView al seleccionar mapa sin NPC

Languages/1.json, Languages/2.json
This pull request updates the cost associated with publishing a character in the application. The changes ensure consistency across different language files by increasing the deduction amount from 20,000 to 35,000 gold coins.
Localization updates:
* [`Languages/1.json`](diffhunk://#diff-c095816dc41d76343121e4679e7617b5f474b5b2549e82ac564ad70f21e49274L157-R157): Updated the Spanish localization for `MENSAJE_PUBLICAR_PERSONAJE_COSTO` to reflect the new deduction amount of 35,000 gold coins.
* [`Languages/2.json`](diffhunk://#diff-aa7a86f241871d4083a745fd57eff4ba5b391a47536fb893cd8ec8d7af24f74cL157-R157): Updated the English localization for `MENSAJE_PUBLICAR_PERSONAJE_COSTO` to reflect the new deduction amount of 35,000 gold coins.
=> Changed gold mao price

CODIGO/ModLanguage.bas, CODIGO/ModSettings.bas
* Changed the field Localization to Language
* Removed the reading settings from DefaultSettingsFile when the key is not found in CustomSettingsFile aka configuracion.ini. There should be a single configuration file. The custom settings file is causing confusion.
=> Default language the same as OS language

CODIGO/Protocol.bas, CODIGO/frmGuildAdm.frm, CODIGO/frmQuestInfo.frm
HandleGuildChat fue modificado para interpretar un nuevo formato enviado por el servidor:
Se recibe el status del mensaje (Byte).
Se recibe un localeId (Integer) que identifica el mensaje localizado.
Se recibe una cadena extra (String) con los parámetros dinámicos (ej: nombres, frases).
Campo  | Tipo      | Descripción
status    |  Byte     | Tipo de mensaje o estado (llegada, salida)
localeId | Integer  | ID del mensaje localizado (Msg2037)
extra      | String   | Texto con parámetros dinámicos (¬1, etc.)
=> Cambios en el cliente (nuevo formato de mensajes de clan localizados)

CODIGO/Protocol.bas, Languages/1.json, Languages/2.json
Cambios realizados:
Se añadió "EMPTY_LABEL": "(Vacío)" en 1.json (Español).
Se añadió "EMPTY_LABEL": "(Empty)" en 2.json (Inglés).
Uso del ID JsonLanguage.Item("EMPTY_LABEL") en el cliente.
=> Agrego mensaje EMPTY_LABEL a JsonLanguage (1.json y 2.json)

CODIGO/frmCustomKeys.frm, CODIGO/frmOpciones.frm, CODIGO/modBindKeys.bas
Este cambio agrega la posibilidad de configurar atajos de teclado para las siguientes acciones del juego:
-Activar/desactivar sonidos
-Activar/desactivar música
Estas acciones ahora pueden ser bindeadas por los usuarios desde Ajustes > Configurar teclas.
=> Atajos de teclado para sonido y musica

CODIGO/TileEngine_Map.bas, CODIGO/clsTexManager.cls, CODIGO/engine.bas, CODIGO/modDX8Requires.bas
Remove mFreeMemoryBytes and clean up obsolete memory-tracking logic
When failing to load a texture due to OUT_MEM we evict only 10 textures if they have not been referenced in 1 min
Delete the mFreeMemoryBytes field and all associated increments/decrements.
Remove free-memory checks and updates from GetTexture, CreateDirect3DTexture, and RemoveLRU.
Simplify OOM handling to rely solely on D3D’s failure/retry path instead of manual byte-count tracking.
Eliminate dead code paths and comments related to the old memory counter.
Result: texture eviction and OOM recovery now use only ReleaseMemory and D3D return codes, streamlining the texture manager.
Load texture in video memory using D3DPOOL_DEFAULT instead of D3DPOOL_MANAGED
=> Refactored clsTexManager

CODIGO/Declares.bas, CODIGO/TileEngine_Map.bas, CODIGO/ao20config.bas
* Inject logic in the map‐transition path to convert `SurfaceDB.GetAllocatedBytes()` (bytes) into megabytes (`usedMB`) by dividing by 1,048,576.
* Compare `usedMB` against the existing `TexHighWaterMark` (already in MB) before calling `SurfaceDB.ReleaseUnusedTextures NumTexRelease`.
* Added `usedBytes` and `usedMB` locals to hold the raw and converted values, respectively.
* Emit a debug print that shows the converted MB usage, the threshold, and how many textures will be released.
* Ensures eviction only occurs when texture memory in MB exceeds the configured high‐water mark.
=> Add TexHighWaterMark‐based eviction threshold

CODIGO/clsTexManager.cls
* Reworked `GetTexture` to use the new ad-hoc hashtable bucket structure (`TexList` with `.SurfaceEntry` arrays) instead of the `Scripting.Dictionary` approach.
* Removed per‐call hit/miss timing logs for cleaner output.
* Implemented direct bucket scanning for cache hits and appending logic for cache misses.
* Ensured new texture metadata (`UltimoAcceso`, width, height, size) is stored in the same structure on load.
* Updated memory usage and texture count tracking in line with the new data structure.
* Preserves original method signature and public behavior while aligning with the custom hashtable storage model.
=> Refactor GetTexture for ad-hoc hashtable implementation

CODIGO/Protocol.bas
Agrego el signo "%" a la resistencia mágica para que se muestre correctamente.
=> Mostrar correctamente el porcentaje en la resistencia mágica

CODIGO/Protocol.bas
Saco el punto (.) para que el mensaje MENSAJE_SEGURO_CLAN_ACTIVADO se muestre correctamente en consola.
=> Fix mensaje seguro de clan activado

CODIGO/General.bas
We must load ResourcesPassword at the very beginning of the execution before trying to load any asset, otherwise the code to decrypt will fail.
=> fix: resource loading failed due to invalid PASSWD

CODIGO/TileEngine_Map.bas, CODIGO/engine.bas
Updated frame advancement logic in TileEngine_Map.bas and engine.bas to multiply elapsed time by 0.5 when calculating animation frames. This change affects all relevant drawing and rendering routines to ensure consistent frame progression.
=> Adjust frame calculation with 0.5 multiplier

CODIGO/Protocol.bas
Anteriormente, la cabeza se dibujaba desalineada (demasiado abajo), debido a que el HeadOffsetY provenía directamente de BodyData y no estaba calibrado correctamente.
Se aplicó un ajuste manual al offset para que la cabeza quede correctamente posicionada sobre el cuerpo.
=> Corrección del offset de la cabeza en los carteles de NPC
