CODIGO/clsGuildDlg.cls
CODIGO/frmMain.frm

Hola!
Este PR es una simple mejora basada en una sugerencia que tuvo bastantes votos positivos en el canal de discord.
Ojalá esto inspire a más personas a contribuir al proyecto.
Si es necesario cambiar algo, estoy a su disposición. Saludos

Make guild chat visible when guild chatbox is open

---

CODIGO/Animations.bas
CODIGO/engine.bas

Fix new animation system to render with the alpha from prev versions

Fix animation alpha

---

CODIGO/TileEngine_Map.bas

Saco árboles de la transparencia, esto esta hardcodeado deberiamos sacarlos a un *.ini

Fic Arbol nuevo continente

---

CODIGO/Protocol.bas
CODIGO/ProtocolCmdParse.bas
CODIGO/Protocol_Writes.bas

Add interface for GM to setup global lobby for events

Add settings and command for lobby

---

CODIGO/ProtocolCmdParse.bas
CODIGO/Protocol_Writes.bas

request login state for target user to help debug the disconnection issue

Add more data to request for debug commands

---

CODIGO/Protocol.bas
CODIGO/ProtocolCmdParse.bas
CODIGO/Protocol_Writes.bas

Add feature toggle command for admins

Add feature toggle command for admins

---

CODIGO/Protocol.bas
CODIGO/ProtocolCmdParse.bas
CODIGO/Protocol_Writes.bas
CODIGO/frmPanelGm.frm

don't merge to master until this pr is ready: https://github.com/ao-org/argentum20-server/pull/176

remove centinela commands  from client

---

CODIGO/Declares.bas
CODIGO/ModLadder.bas
CODIGO/Protocol.bas
CODIGO/Recursos.bas
CODIGO/TileEngine.bas
CODIGO/TileEngine_RenderScreen.bas
CODIGO/clsGrapchicalInventory.cls

Add fishing pool obj type

---

CODIGO/Declares.bas
CODIGO/frmConnect.frm

Cleaned up a bit the connect screen

Character Transfer WIP

---

Argentum20.vbp
CODIGO/Declares.bas
CODIGO/ModAuth.bas
CODIGO/ModLadder.bas
CODIGO/Protocol.bas
CODIGO/clsGameState.cls
CODIGO/engine.bas
CODIGO/frmConnect.frm
CODIGO/frmCrearPersonaje.frm
CODIGO/frmOpciones.frm

Got rid of `QUERENDER` in favor of g_game_state

Refactored poor code

---

Argentum20.vbp
CODIGO/Declares.bas
CODIGO/General.bas
CODIGO/ModAuth.bas
CODIGO/frmConnect.frm
CODIGO/frmNewAccount.frm
CODIGO/frmPasswordReset.frm
CODIGO/frmTransferChar.frm

Client can now send TRANSFER_CHARACTER_REQUEST and handle reply from server.
UI in progress.
To send a request hold SHIFT and click on BORRAR PJ

TransferChar

---

CODIGO/Declares.bas
CODIGO/ModAuth.bas
CODIGO/frmTransferChar.frm

This patch implements a fully functional char transfer operation in the game client
To transfer a character PRESS SHIFT and CLICK ON DELETE CHAR

TransferChar Frontend

---

Argentum20.vbp
CODIGO/Declares.bas
CODIGO/Graficos_Utilidades.bas
CODIGO/ModUtils.bas
CODIGO/engine.bas
CODIGO/frmConnect.frm
CODIGO/frmConnecting.frm
CODIGO/frmCrearPersonaje.frm
CODIGO/frmOpciones.frm
CODIGO/modDX8Requires.bas
CODIGO/modNetwork.bas

add connection dialog with timeout to retry connection with another ip
move power up time text from screen and add color when time is running out
Disable VSync option since is broken now and user don't understand why they have black screen

add connection retry

---

CODIGO/Animations.bas
CODIGO/FrmGrupo.frm
CODIGO/Protocol_Writes.bas

fix start active animation when loop is active
fix group action (leave group and expel members)

Some fixes

---

Argentum20.vbp
CODIGO/FrmLogear.frm
CODIGO/General.bas
CODIGO/ModLenguaje.bas
CODIGO/ModMetereologia.bas
CODIGO/ModSettings.bas
CODIGO/ModTutorial.bas
CODIGO/ModUtils.bas
CODIGO/Protocol.bas
CODIGO/Recursos.bas
CODIGO/frmOpciones.frm
CODIGO/modBindKeys.bas

Instead of using the same file to download the default settings and save the new values we have now a template settings and a user settings so we don't override the user settings every time we update the default settings files

Update setting file management

---

CODIGO/Protocol.bas

to merge with https://github.com/ao-org/argentum20-server/pull/216

Fix damage over characters text

---

CODIGO/General.bas
CODIGO/frmGuildLeader.frm

Fixed #116
Dejo mi aporte anual al proyecto (?
Saludos y ojalá esto siga creciendo.

Fix guild description contains invalid characters

---

CODIGO/Protocol.bas

Implemented 5 new achievements
Adventurer -> unlocked when user gets to level 10
Seasoned adventurer -> unlocked when user gets to level 20 Big shot -> unlocked when user gets to level 30
You mean business  ->  unlocked when user gets to level 30 Small victory -> when the user hits an NPC

Implemented 5 new steam achievements

---

CODIGO/Recursos.bas
CODIGO/TileEngine_Map.bas
CODIGO/engine.bas

This reverts commit 5c9330e5ab05228cb57dc4a42b1904fb9256e584.

Revert "Fix animacion (#156)"

---

CODIGO/ModUtils.bas
CODIGO/Recursos.bas

Aumento mapas y quest para el minimapa

Aumento mapas y quest para el minimapa

---

CODIGO/Protocol.bas

Removed two packets and related code
UserHitNPC 
UserAttackedSwing

Removed unused packetIDs

---

CODIGO/TileEngine_Map.bas

Fix de Es Arbol

---

CODIGO/TileEngine_Map.bas
CODIGO/TileEngine_RenderScreen.bas

Transparency in quest ship columns

Transparency in quest ship columns

---

CODIGO/FrmLogear.frm
CODIGO/General.bas

New network topology requires changing the addresses

Updated Servers IP Addresses

---

CODIGO/FrmLogear.frm
CODIGO/General.bas

This reverts commit b420ac3bb3f4ba4d111da910e6910912bba6f6f3.

Revert "Updated Servers IP Addresses (#239)"

---

CODIGO/FrmLogear.frm
CODIGO/General.bas

Reverts ao-org/argentum20-client#240

"Updated Servers IP Addresses (#239)"

---

CODIGO/FrmLogear.frm
CODIGO/General.bas

Reverts ao-org/argentum20-client#241

Revert ""Updated Servers IP Addresses (#239)""

---

CODIGO/Protocol.bas
CODIGO/ProtocolCmdParse.bas
CODIGO/Protocol_Writes.bas
CODIGO/frmPanelGm.frm

Cannot be handled by VB server

Removed BanIP code

---

CODIGO/FrmLogear.frm
CODIGO/General.bas

Reverts ao-org/argentum20-client#246

Revert "Revert "Merge pull request #242 from ao-org/revert-241-revert-240-rev…"

---

CODIGO/FrmLogear.frm
CODIGO/General.bas

Reverts ao-org/argentum20-client#247

Revert "Revert "Revert "Merge pull request #242 from ao-org/revert-241-revert-240-rev…""

---

CODIGO/FrmTorneo.frm

Changes FrmTorneo

---

CODIGO/MenuGM.frm
CODIGO/frmPanelGm.frm

Modify GM Panel report and GM Menu add Inventory

MenuGM Inventario

---

CODIGO/Protocol.bas
CODIGO/frmPanelGm.frm

Fix PanelGM

---

Argentum20.vbp

Added missing enviromental variables in the vbp file, Now the project loads without needing any manual modification

Added missing enviromental variables in the vbp file, Now the project loads without needing any manual modification

---

CODIGO/Graficos_Particulas.bas
CODIGO/Protocol.bas
CODIGO/TileEngine.bas
CODIGO/TileEngine_Map.bas
CODIGO/TileEngine_RenderScreen.bas
CODIGO/ao20audio.bas
CODIGO/frmMain.frm
CODIGO/frmOpciones.frm

La lluvia no tenía sonido, solo se escuchaba al terminar.
Arreglé eso y que las partículas de lluvia caigan lento al principio.
También revisé que funcione bien el cambio de mapa (creo que es fix ao-org/argentum-online-server#457) y salir/entrar debajo de un techo.
Dejo algunas anotaciones para explicar otros cambios y si algo no se entiende me preguntan.
Saludos

Fix sonido de la lluvia y partículas

---

CODIGO/Protocol.bas

Introduje el error en el merge #303

Fix error: el cliente no cierra por completo

---

CODIGO/Recursos.bas

Una pena que estos valores estén hardcodeados y no se lean de un archivo :S

Fixes #308 la animación de meditar se congela

---

CODIGO/ModAuth.bas

When the client is an old build we show the correct error message asking the user to update the client

Improve error msg

---

CODIGO/General.bas
CODIGO/Protocol.bas
CODIGO/TileEngine.bas
CODIGO/ao20audio.bas

Los arreglos acá vienen de la mano con los de los del servidor.
El principal error era borrar el char cuando estaba invisible y fuera de rango.
Después estaba el tema que el cálculo de distancia en el cliente no era el mismo que el servidor...
Como cambio adicional, me puse a jugar un poco con el sonido de los pasos (nuevamente) y encontré que fuera de la pantalla no se escuchaba ninguno. Arreglé eso y también jugué un poco con la atenuación del volúmen con la distancia, ya que la diferencia entre los pasos del personaje propio y el de otro al borde de la pantalla era muy grande.
Esto se puede probar e ir cambiando para que quede mejor.

Fix invisibilidad

---

CODIGO/frmQuestInfo.frm

Me dejé un 1 hardcodeado en vez de la variable iterativa

Fix indice quests

---

CODIGO/ModGameplayUI.bas

Remuevo el código de la acción de usar items.
Arreglo el resto de acciones que no estaban funcionando. Limpio el código.

Fix acciones del mouse

---

CODIGO/Declares.bas

Reverts ao-org/argentum-online-client#339
Revierto a pedido de @ReyarB

Revert "caminata Ghost"

---

CODIGO/engine.bas

Prueba Cambios Rey Texto Fixed

Prueba Cambios Rey Texto Fixed

---

CODIGO/engine.bas

Arreglo Body y Head Gulfas Morgolock 💯

Update Head Casco Gulfas

---

CODIGO/frmOpciones.frm

Por favor borrar anterior branch

Remuevo Recuperar Contraseña

---

CODIGO/ModLogin.bas

Arregla la ventana de crear cuenta cuando aparece la ventana de selección de personajes

Refactor code to unload login and account forms if visible

---

CODIGO/modBindKeys.bas

Fix issue with missing DefaultKeyMappingFile in modBindKeys.bas, loop Error

Fix issue with missing DefaultKeyMappingFile in modBindKeys.bas

---

CODIGO/ModTutorial.bas
CODIGO/Protocol.bas
CODIGO/TileEngine_Map.bas
CODIGO/frmConnect.frm

Fix head & body position and size

Fix cartel quest

---

CODIGO/ModUtils.bas
CODIGO/frmConnect.frm
CODIGO/frmCrearPersonaje.frm

Deleted restriction for Forgat, now we can select the city.

Deleted restriction for selection of city at character creation

---

CODIGO/Protocol.bas
CODIGO/frmGuildBrief.frm

Adaptación de la ventana (frmGuildBrief) para usar con la interfaz que subi a Recursos
@RecoX

Ventana frmGuildBrief

---

CODIGO/Protocol.bas

Added timestamps to /gm requests.
Evidence:

[ISSUE-570] [CLIENTE] Agregarle fecha y hora a la consulta que nos llegan al PanelGM

---

CODIGO/FrmSastre.frm
CODIGO/frmHerrero.frm

Ventana Herreria

---

CODIGO/FrmSastre.frm
CODIGO/frmHerrero.frm

Herreria y Sastreria

---

CODIGO/FrmSastre.frm

Arreglo de movimiento de la ventana y agregue el sonido y efecto del botón cerrar

Arreglo ventana Sastreria

---

CODIGO/frmShopPjsAO20.frm

Había quedado con el valor viejo y ahora modifiqué el Form con el valor actual de 20.000 monedas de oro.

Actualización de precio en FORM de VentadePjs

---

CODIGO/engine.bas
CODIGO/frmMain.frm

Hace mucho tiempo se ha desactivado la opción de PING del servidor, por sugerencia de @ccmercuri subo PR para que no muestre más el texto MS.

Ocultar el label que informa ping en ms en el frmMain.frm

---

Languages/1.json
Languages/2.json

se una en varios mensajes despues agregamos mas personalizados

fix en mensaje json

---

CODIGO/Protocol.bas

Actualizo la cantidad máxima de miembros de clan permitida que se muestra en el cliente, según el nivel del clan

Actualizo max. miembros de clan

---

CODIGO/frmConnect.frm

This pull request includes changes to the `CODIGO/frmConnect.frm` file to improve code readability and clarity by renaming variables to be more descriptive.
Code readability improvements:
* Renamed the variable `Char` to `SelectedCharIndex` to make its purpose clearer.
* Updated the assignment of `PJSeleccionado` to `SelectedCharIndex` for consistency with the new variable name.

Fixed missing SelectedCharIndex

---

CODIGO/FrmEstadisticas.frm

Cambio de ubicación en algunos skills de la ventana frmEstadisticas. Para que se vea correctamente es necesario utilizar las imágenes de interfaz subidas a Recursos.

Cambios en frmEstadisticas

---

CODIGO/frmOpciones.frm
Languages/1.json
Languages/2.json

Pude arreglar link a la home de ArgentumOnline
Queda una linea en blanco en la configuracion de Video (ToDo @ReyarB)
Revisen por favor si el resto está bien borrado, espero que vuelva Rey para poder arreglar esa linea blanco del Form.

Fix opciones

---

CODIGO/General.bas
CODIGO/ModTaehcitna.bas
CODIGO/ModUtils.bas
CODIGO/engine.bas
CODIGO/frmConnect.frm
CODIGO/modNetwork.bas

Removed efectoSangre() no longer needed

DirectPlay login new char implemented

---

CODIGO/clsCursor.cls

This pull request includes significant changes to the `Parse_Form` method in the `CODIGO/clsCursor.cls` file. The main improvements involve refactoring the cursor handle determination logic, simplifying the control loop, and enhancing error logging.
Key changes include:
* Refactored the cursor handle determination logic from a separate function into a `Select Case` statement directly within the `Parse_Form` method. This change eliminates the need for the `GetCursorHandle` helper function.
* Simplified the control loop by removing the `SupportsMouseProperties` check and the associated error handling for unsupported controls. This results in a more streamlined loop that directly sets the `MouseIcon` and `MousePointer` properties.
* Enhanced the error logging mechanism to include the exact …

Removed unnecesary logs and checks in mouse pointer

---

CODIGO/FormInvi.bas
CODIGO/frmConnect.frm

Also fixed a bug with the particles. We can't call Engine_Select_Particle_Set in Form_Activate() because the array has not been initialized.

Enabled window border for DEBUGGING

---

CODIGO/Protocol_Writes.bas
CODIGO/clsNetWriter.cls
CODIGO/frmConnect.frm
CODIGO/modDplayClient.bas
CODIGO/modNetwork.bas

Handle desconnection from Server properly and go back to the main menu

Various fixes DPLAY

---

CODIGO/AO20CryptoSysWrapper.bas
CODIGO/ModUtils.bas
CODIGO/PacketId.bas
CODIGO/clsNetWriter.cls
CODIGO/modDplayClient.bas
CODIGO/modNetwork.bas

Various fixes for DPLAY
Added the debugging feature to dump sent packets to send_dbeug.txt which is very useful to understand some problems that may occur
Improved error handling: added more DPERR codes

DPLAY fixes

---

CODIGO/Protocol.bas

Con este cambio se ocultan los mensajes de meditación si la pestaña "INFO" está desactivada.

Ocultar mensajes de meditación

---

CODIGO/engine.bas
CODIGO/modNetwork.bas

Removed DPNOP_SYNC to try to improve latency

DPLAY: Removed DPNOP_SYNC flag

---

CODIGO/Protocol.bas
CODIGO/frmGuildLeader.frm

Actualizo los beneficios de clan en la ventana del lider y acomodo algunos detalles para que se muestren mejor

Actualización de beneficios de clan en la ventana del lider

---

CODIGO/frmMain.frm

adding missing exit sub

---

CODIGO/ModUtils.bas
CODIGO/Protocol.bas
CODIGO/frmQuestInfo.frm

De ser necesario, se muestra en los requisitos de la quest el nivel máximo. Necesario:  https://github.com/ao-org/argentum-online-server/pull/728

Mostrar nivel máximo requerido en quest

---

CODIGO/frmMensajePapiro.frm

Actualizo los links que estaban desactualizados en la cartelera

Actualización links de cartelera

---

CODIGO/Group.bas

* Removed call to draw non existent GRH
* Added offset to render the head next to the name

Fixed party render

---

CODIGO/frmMain.frm

Cambio ubicación de OnLine solo GMs

Cambio ubicación de OnLine solo GMs

---

CODIGO/frmMapaGrande.frm

- Ahora la llamada de clan (G) se muestra correctamente en el mapa

Fix llamada de clan

---

CODIGO/MenuGM.frm

Faltaba mandar el Nombre del PJ

Fix en /SUM

---

CODIGO/frmOpciones.frm

Make sure the scrollbar control value is withing {min,max}

Fix volume settings

---

CODIGO/Protocol.bas

Si esta el mini juego no se puede volver a pescar.

Si esta el mini juego no se puede volver a pescar

---

Languages/1.json
Languages/2.json

Corrección en la línea 74 en ambos lenguajes

Fix Languajes

---

CODIGO/ModGameplayUI.bas
CODIGO/frmMain.frm

Fix Palabra invenroty X inventory

---

CODIGO/ProtocolCmdParse.bas

accepts the command in Spanish or English

case selection in SP and EN

---

CODIGO/General.bas
CODIGO/Protocol.bas
CODIGO/frmCrearPersonaje.frm
CODIGO/frmGuildDetails.frm

Cleaned up
Replaced MsgBox with frmDebug.add_text_tracebox

Removed unused HandleForceUpdate

---

CODIGO/ProtocolCmdParse.bas

Fix en traducción comando

---

Languages/1.json

Deseas abrir el navegador ahora

fix Deseas abrir el navegador ahora

---

CODIGO/Protocol.bas

- Removed all Err.Raise calls for packet corruption or unrecognized IDs
- On “Case Else”, now log unknown PacketId via RegistrarError and drain any remaining bytes
- After dispatch, detect any leftover buffer bytes (too-many-bytes) and: • Log detailed error with RegistrarError(&HDEADBEEF,…) • Consume extra bytes in a loop to keep reader in sync
- Ensure HandleIncomingData returns True for malformed or unknown packets so the client doesn’t crash
- Preserved original VB error handler to catch only genuine runtime errors and return False
- Added inline comments to explain the new logging, draining, and success-return logic

Gracefully handle malformed and unknown packets in HandleIncomingData

---

CODIGO/ProtocolCmdParse.bas

Modifico Salir en ingles

---

CODIGO/Declares.bas
CODIGO/Graficos_Particulas.bas
CODIGO/PacketId.bas
CODIGO/Protocol.bas
CODIGO/Recursos.bas
CODIGO/frmConnect.frm
CODIGO/frmCrearPersonaje.frm
CODIGO/frmMain.frm
CODIGO/modBindKeys.bas

I delete unnecessary commented lines

I delete unnecessary commented lines

---

CODIGO/MenuGM.frm

Mensajes automaticos para control de Macros

Msg Para GMs

---

CODIGO/frmAlqui.frm

- Ventana de alquimia: ahora se puede deslizar por la pantalla con el mouse al igual que la de Carpintería, Sastrería y Herrería.

Movimiento de la ventana con el mouse

---

CODIGO/Protocol.bas
Languages/1.json
Languages/2.json

"Fallas", "Falló"

---

CODIGO/ProtocolCmdParse.bas
CODIGO/clsGrapchicalInventory.cls
Languages/1.json
Languages/2.json

Fix BAN MSG

---

CODIGO/Protocol.bas
CODIGO/frmShop.frm
Languages/1.json
Languages/2.json

"Fix for the missing word 'value' in the shop menu of the Mesón Hostigado. JSON was used to handle the text in both Spanish and English."

"Corrección por falta de la palabra 'valor'

---

CODIGO/ModAuth.bas

"Replaced static DisplayError messages with IDs to enable localization and facilitate multi-language support."

IDs en mensajes de DisplayError

---

CODIGO/PacketId.bas
CODIGO/Protocol.bas

Removed the IDs
1) eRequestTelemetry
2) eForceUpdate

Removed PacketIDs no longer used

---

Languages/1.json
Languages/2.json

Nuevos ids de mensajes que se usan con el sistema de chat faccionario

Ids de mensajes para chat faccionario

---

CODIGO/PacketId.bas
CODIGO/Protocol_Writes.bas

Removed eSendTelemetry and WriteSendTelemetry

Fixed compiler error

---

CODIGO/ModGameplayUI.bas
CODIGO/PacketId.bas
CODIGO/Protocol.bas
CODIGO/ProtocolCmdParse.bas
CODIGO/Protocol_Writes.bas
CODIGO/frmMain.frm
CODIGO/frmMensaje.frm

Implemento sistema de chat faccionario por consola
Con esta implementación, los usuarios pertenecientes a una facción podrán comunicarse entre ellos a traves del comando /FMSG.
Necesario aceptar PR en servidor: https://github.com/ao-org/argentum-online-server/pull/830

Feat: Chat faccionario

---

CODIGO/Protocol_Writes.bas

Cambio de byte a integer el tipo de variable para el tiempo de cárcel.

Cambio en el tipo de variable para el tiempo de cárcel

---

Languages/1.json
Languages/2.json
Languages/3.json
Languages/4.json
Languages/5.json

Actualizo los ids de mensajes para la boveda.

Ids de mensajes para boveda

---

CODIGO/ModUtils.bas
CODIGO/frmQuestInfo.frm

-fixed data types that didn't match Writer data types from server (a lot of uncontrolled type casts where being done)

fix_QuestsGreaterThan255InFrmQuests

---

CODIGO/Protocol.bas

Added the newly declared messages to the Languages.

Add Message For LegionaryButton

---

CODIGO/Protocol.bas

Wip multilenguaje prepare localized chat over head

Improved localization: chat over head

---

CODIGO/frmOpciones.frm

Replaced SND_RESUCITAR with SND_DICE for a more suitable sound.

Update volume adjustment sound effect

---

Argentum20.vbp

Updated the url and game name on .exe's info 
@morgolock @RecoX

Update url and legal trademarks on .exe.

---

CODIGO/ao20config.bas

Fix a little but noisy error on config's loading.

Fix load config to avoid error on loading.
